### ISSUE TITLE
Множественный возврат

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/LifeGame#10]
Методы не должны использовать множественный возврат. Если метод должен возвращать значение, то оператор `return` должен в нем встречаться только один раз.

Методы, в которых данное правило не соблюдается:
- `LifeGame.EndGameRules.endAllDead`.
- `LifeGame.EndGameRules.EndRepeatTurns`.
- `LifeGame.Universe.update`.

**Comment by Snez0K** [comment]
WHy ?

**Comment by Snez0K** [comment]
это ж типо Bool метод, в нем так и просится в одном случае true, в другом False

**Comment by truenorthpaul** [comment]
У функции всегда должна быть одна точка входа и одна точка выхода. Это самая правильная структура кода. Преждевременный возврат не дает никакого выиграша, а только нарушает естественный поток кода.
