### ISSUE TITLE
Замена метода на свойство

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/LifeGame#15]
Методы, которые стоит заменить свойствами:
- `LifeGame.Style.getAlive`.
- `LifeGame.Style.getBorder`.
- `LifeGame.Style.getCursor`.
- `LifeGame.Style.getDead`.
- `LifeGame.Style.getWillBorn`.
- `LifeGame.Style.getWillDie`.

**Comment by Snez0K** [comment]
fixed https://github.com/Snez0K/LifeGame/commit/2bc34cb1cbfec91338daa0c582c968b53a61ad01

**Comment by truenorthpaul** [comment]
Методы, которые стоит заменить свойствами:
- `LifeGame.Universe.GetTimer`.
