### ISSUE TITLE
Неинформативные идентификаторы

### ISSUE THREAD

**Issue by truenorthpaul** [Snez0K/LifeGame#17]
Идентификаторы должны быть информативны и описывать свое предназначение. 

Поля, для идентификаторов которых данное правило не соблюдается:
- ` LifeGame.EndGameRules.result`.

Переменные, для идентификаторов которых данное правило не соблюдается:
- `result` (метод `LifeGame.EndGameRules.EndRepeatTurns`).

**Comment by truenorthpaul** [comment]
Поля, для идентификаторов которых данное правило не соблюдается:
- `LifeGame.Command.CommandFactory.result`.
- `LifeGame.EndGameRules.list`.

Переменные, для идентификаторов которых данное правило не соблюдается:
- `result` (метод `LifeGame.EndGameRules.EndRepeatTurns`).

**Comment by PavelDubsky** [comment]
Поля, для идентификаторов которых данное правило не соблюдается:
- `LifeGame.Command.CommandFactory.result`.

**Comment by truenorthpaul** [comment]
Поля, для идентификаторов которых данное правило не соблюдается:
- `LifeGame.Command.CommandFactory.list`.
- `LifeGame.EndGameRules.result`.

Методы, для идентификаторов которых данное правило не соблюдается:
- `LifeGame.Command.CommandFactory.Factory`.
- `LifeGame.Universe.Tempgenerate`.

Переменные, для идентификаторов которых данное правило не соблюдается:
- `i` (метод `LifeGame.Universe.Pregame`).
- `list` (метод `LifeGame.Universe.Pregame`).
- `map2` (метод `LifeGame.Universe.Update`).
- `result` (метод `LifeGame.Universe.Update`).
